---
title: "OHI `r format(Sys.Date(), '%Y')` - Aquarium Fishing Livelihoods & Economies Data Preparation"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
pdf_document:
  toc: true
editor_options: 
  chunk_output_type: inline
  markdown: 
    wrap: 72
---

# Livelihoods: Proportion of Tourism Jobs per Country/Region per Year

## Overview

* **Data:** Labor Force & Employment Data

  * Labor Force data from World Bank (downloaded June 28. 2024)

      - https://data.worldbank.org/indicator/SL.TLF.TOTL.IN
      
  * ILOSTAT (downloaded July 2, 2024) -- for tour/cf wage data
  
      - https://rshiny.ilo.org/dataexplorer46/?lang=en&id=EAR_4MTH_SEX_ECO_CUR_NB_A 


### Setup

```{r}
# load packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  here,
  janitor,
  terra,
  countrycode,
  readxl,
  RColorBrewer,
  foreach,
  doParallel, # for using multiple cores
  tidyverse, 
  httr,
  plotly,
  zoo # for gapfilling
  
)
#remotes::install_github("skgrange/threadr") # for na_extrapolate
library(threadr)


# source 
source(here("workflow", "R", "common.R"))
# used to clean FAO online portal data
# source(here("workflow", "R", "fao_online_portal_clean.R")) # old function
source(here("workflow", "R", "fao_query_data_tidy.R")) # new function

# set year and file path info
current_year <- 2024 # Update this!!

version_year <- paste0("v",current_year)
data_dir_version_year <- paste0("d", current_year)
data_path <- here("globalprep", "le", version_year)

# Raw data directory (on Mazu)
raw_data_dir <- here::here(dir_M, "git-annex", "globalprep", "_raw_data")

# world bank raw data directory
wb_dir <- here(raw_data_dir, "WorldBank", data_dir_version_year)
fao_comm_dir <- here(raw_data_dir, "FAO_commodities", data_dir_version_year)


# output data dir for intermediate data products
int_dir <- here(data_path, "int")
```


Create country code --> iso3 function

```{r}
library(countrycode)

country_regex_to_iso3c <- function(country_string) {
  country_string %>%
    countrycode::countrycode(origin = "country.name", destination = "iso3c", origin_regex = TRUE)
}
```

## Read in Data

```{r}
# OHI regions data ----
# read in OHI regions for joining
region_names <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/eez/spatial/regions_list.csv") %>% 
  janitor::clean_names() %>% 
  select(-notes)

# labor force from World Bank (cleaned, joined with OHI regions)
labor_force <- read_csv(here(int_dir, "labor_force.csv"))

# Aquarium Fishing FAO data 
commodities_value_raw <- read_csv(here(fao_comm_dir, "query_portal", "trade_partners_value.csv"))

```
```{r}
# check and see if any values are considered negligible
commodities_value_raw %>% filter(`2021 Flag` == "N")
```


## Data cleaning & Wrangling

```{r}
# adapted from the v2023 livelihood_economies_dataprep.Rmd
fao_latest_data_year <- 2021 # update to the last year available in FAO data, likely the same for all FAO data included.

# clean up commodities value data for ornamental fishing revenue
ornamental_value <- commodities_value_raw %>%
  janitor::clean_names() %>% 
  # filter to ornamental commodities 
  filter(str_detect(commodity_name_en, "Ornamental")) %>% 
  rename(country = "reporting_country_name_en", 
         partner_country = "partner_country_name_en",
         commodity = "commodity_name_en",
         trade = "trade_flow_name_en") %>%
  filter(trade == "Exports" & commodity != "Ornamental freshwater fish") %>% # remove all other fish (commodities) that are not ornamentals (bc aquarium = ornamental), don't include the freshwater ornamental fish (interested in saltwater/ocean only)
  # fao cleaning function found in workflow/R
  fao_query_data_tidy(initial_data_year = 2019,
                          last_data_year = 2021) %>% # used function to clean and pivot data, remove Flag columns (definitely check out this script!)
  mutate(value = (value * 1000), # convert from thousands to single dollar 
         unit = "USD (1)") %>% 
  # add iso3 column
  mutate(iso3 = country_regex_to_iso3c(country)) # get iso3 code of reporting country
```



```{r}
# sum for each country 
ornamental_revenue <- ornamental_value %>% 
  group_by(country, year) %>% 
  summarize(value = sum(value, na.rm = TRUE),
            unit = first(unit)) %>% 
  mutate(sector = "aqf", # code for aquarium fishing sector
         data_source = "FAO global trade") %>% 
  select(country, year, value, unit, sector, data_source) %>% 
  # add iso3 column
  mutate(iso3 = country_regex_to_iso3c(country)) %>%  # get iso3 code of reporting country
  relocate(iso3, .after = country)

# write as intermediate file
write_csv(ornamental_revenue, here(int_dir, "aqf_revenue.csv"))


```

