---
title: "OHI Economies Dataprep"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
pdf_document:
  toc: true
editor_options: 
  chunk_output_type: inline
  markdown: 
    wrap: 72
---

------------------------------------------------------------------------


# Economies Dataprep (Measures the amount of revenue produced)

## Overview

-   **Data:**

    -   Tourism: UNWTO Dept. of Statistics (UN Tourism)
        -   https://www.unwto.org/tourism-statistics/economic-contribution-SDG 

### Setup

```{r}
# load packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  here,
  countrycodes,
  janitor,
  terra,
  readxl,
  RColorBrewer,
  foreach,
  doParallel, # for using multiple cores
  tidyverse, 
  httr,
  plotly,
  zoo # for gapfilling
  
)
#remotes::install_github("skgrange/threadr") # for na_extrapolate
library(threadr)


# source 
source(here("workflow/R/common.R"))

# set year and file path info
current_year <- 2024 # Update this!!

version_year <- paste0("v",current_year)
data_dir_version_year <- paste0("d", current_year)
data_path <- paste0("globalprep/le/", version_year)

# Raw data directory (on Mazu)
raw_data_dir <- here::here(dir_M, "git-annex", "globalprep", "_raw_data")

# UNWTO raw data directory
unwto_dir <- here(raw_data_dir, "UNWTO", data_dir_version_year)
```


### Tourism

#### Read in Data

```{r}
# ===================== Read in Data ==============================


# Tourism revenue data ----
gdp_prop_raw <- readxl::read_xlsx(here(unwto_dir, "Indicator-8_9_1-2022-UN_Tourism_april2024_update.xlsx"))

# OHI regions data ----
region_names <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/eez/spatial/regions_list.csv") 
```


## Data cleaning

"Tourism direct GDP as a proportion of total GDP (%)"


```{r}
# make countrycode -- iso3 function ----
# following this example on Rpubs: https://rpubs.com/Teal_Emery/cleaning_intl_data_tips_and_tricks 
country_regex_to_iso3c <- function(country_string) {
  country_string %>%
    countrycode::countrycode(origin = "country.name", destination = "iso3c", origin_regex = TRUE)
}

# GDP proportion dataset cleaning ----
gdp_prop_clean <- gdp_prop_raw %>% 
  janitor::clean_names() %>% 
  select(c(geo_area_name, year = time_period, gdp_prop_percent = total)) %>% 
  mutate(sector = "tour") %>% 
  # add iso3 column
  mutate(iso3 = country_regex_to_iso3c(geo_area_name))


# preliminary plotting ----
prelim_plot <- plot_ly(data = gdp_prop_clean, x = ~year, y = ~gdp_prop_percent, color = ~geo_area_name, 
                       type = "scatter", mode = "lines") %>% 
  layout(title = "Tourism direct GDP as a proportion of total GDP (%) for All Geo Regions",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Tourism Contribution to GDP (%)"))

prelim_plot

htmlwidgets::saveWidget(prelim_plot, file = "gdp_prelim_plot_all_years.html")
```



### Join with OHI regions

```{r}
# tidy up regions dataset ----
region_names <- region_names %>% select(-Notes)

# join regions & tourism GDP prop ----
gdp_regions_join <- left_join(region_names, gdp_prop_clean, by = c("eez_iso3" = "iso3"))



```

