---
title: "OHI `r format(Sys.Date(), '%Y')` - Mariculture Livelihoods & Economies Data Preparation"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
pdf_document:
  toc: true
editor_options: 
  chunk_output_type: inline
  markdown: 
    wrap: 72
---

# Livelihoods: Proportion of Tourism Jobs per Country/Region per Year

## Overview

* **Data:** Labor Force & Employment Data

  * Labor Force data from World Bank (downloaded June 28. 2024)

      - https://data.worldbank.org/indicator/SL.TLF.TOTL.IN
      
  * ILOSTAT (downloaded July 2, 2024) -- for tour/cf wage data
  
      - https://rshiny.ilo.org/dataexplorer46/?lang=en&id=EAR_4MTH_SEX_ECO_CUR_NB_A 


### Setup

```{r}
# load packages
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  here,
  janitor,
  terra,
  readxl,
  RColorBrewer,
  foreach,
  doParallel, # for using multiple cores
  tidyverse, 
  httr,
  plotly,
  zoo # for gapfilling
  
)
#remotes::install_github("skgrange/threadr") # for na_extrapolate
library(threadr)


# source 
source(here("workflow/R/common.R"))

# set year and file path info
current_year <- 2024 # Update this!!

version_year <- paste0("v",current_year)
data_dir_version_year <- paste0("d", current_year)
data_path <- here("globalprep", "le", version_year)

# Raw data directory (on Mazu)
raw_data_dir <- here::here(dir_M, "git-annex", "globalprep", "_raw_data")

# world bank raw data directory
wb_dir <- here(raw_data_dir, "WorldBank", data_dir_version_year)

fao_dir <- here(raw_data_dir, "FAO_mariculture", data_dir_version_year)

aquaculture_value <- read_csv(file.path(dir_M, "git-annex/globalprep/_raw_data/FAO_mariculture/d2023/online_query_portal/FAO_GlobalAquacultureProduction_Value_1984_2021.csv"))

aquaculture_value2 <- read_csv(file.path(fao_dir, "/FAO_GlobalAquacultureProduction_Value_1984_2022.csv"))


# output data dir for intermediate data products
int_dir <- here(data_path, "int")
```



## Read in Data

```{r}
# OHI regions data ----
# read in OHI regions for joining
region_names <- read_csv("https://raw.githubusercontent.com/OHI-Science/ohi-global/draft/eez/spatial/regions_list.csv") %>% 
  janitor::clean_names() %>% 
  select(-notes)

# FAO Aquaculture data ----
aquaculture_value <- read_csv(file.path(fao_dir, "/FAO_GlobalAquacultureProduction_Value_1984_2022.csv")) %>% 
  janitor::clean_names()
# str(aquaculture_value)
```


```{r}
#clean the aquaculture value data
#this will also be used in the mariculture jobs data section, so need to keep in all environments in the first step
aquaculture_value_clean <- aquaculture_value %>% 
   dplyr::rename(country = country_name,
                species =  asfis_species_name,
                area = fao_major_fishing_area_name,
                environment = environment_name) %>%
  dplyr::select(-c(unit_name))  %>% #clean data, note that we are still using a sub_n value of .1 (100 dollars) 
  mutate(row_id = row_number())

initial_data_year = 1984
last_data_year = 2022

test = paste0("x", initial_data_year:last_data_year)

flag_start = 8
flag_end = 84
test = paste0("symbol_", seq(flag_start, flag_end, by = 2))

fao_values <- aquaculture_value_clean %>% 
  # dplyr::select(-c(paste0("symbol_", seq(flag_start, flag_end, by = 2)))) %>% 
  pivot_longer(cols = paste0("x", initial_data_year:last_data_year),
               names_to = "year",
               values_to = "value") %>% 
  pivot_longer(cols = paste0("symbol_", seq(flag_start, flag_end, by = 2)),
               names_to = "flag_year",
               values_to = "flag")
sub_N = 0.1

fao_new <- fao_values %>% 
  mutate(value = case_when((str_detect(flag, "N") & value == 0) ~ sub_N,
                           TRUE ~value)) %>% #replace values that are 0 and have the flag N with sub_N
  select(-c(row_id, flag, flag_year))


#filter to only marine habitats
 mariculture_revenue <- aquaculture_value_clean %>% 
   filter(environment %in% c("Brackishwater", "Marine"))

#sum by region and year (we need total revenue)
total_mar_rev <- mariculture_revenue %>%
  group_by(country, year) %>% 
  summarize(value = sum(value, na.rm = T)) %>% 
  mutate(sector = "mar", data_source = "FAO aquaculture value", unit = "USD (1)",
          value = value *1000) %>% #multiply value times 1000 to get dollars
  select(country, year, value, unit, sector, data_source)

write_csv(total_mar_rev, here(data_path, "int/mar_revenue.csv"))
```














