


```{r}
library(ohicore) #devtools::install_github('ohi-science/ohicore@dev')
library(dplyr)
library(stringr)
library(tidyr)
library(Hmisc)
library(here)
library(validate)
library(tidyverse)
library(readxl)

source(here("workflow/R/common.R"))
```




```{r}

spi_calc <- read.csv(here("globalprep/prs_res_spi/v2022/int/Country_spi.csv"), stringsAsFactors = FALSE)

spi_calc <- spi_calc %>%
  mutate(Country = case_when(
   Country=="Côte d'Ivoire" ~ "Ivory Coast",
    Country=="R<e9>union" ~ "Reunion",
    Country=="Cura<e7>ao" ~ "Curacao",
    Country=="Korea, Democratic Republic of" ~ "North Korea",
    Country=="St. Helena" ~ "Saint Helena",
    Country=="St. Martin" ~ "Northern Saint-Martin",
    TRUE ~ Country # Everything else, leave it be
    ))

# Channel Islands are Jersey and Guernsey, but these are already in the data

spi_rgn <- name_2_rgn(df_in = spi_calc, 
                       fld_name='Country',
                      flds_unique = c("year"))

# Weight the following duplicates by population
# China, Guadeloupe, Guam, Hong Kong, Macao, Martinique, Northern Mariana Islands, Puerto Rico, Virgin Islands (U.S.)... Populations taken from google

pop_weights <- data.frame(Country = c("China", "Hong Kong", "Macao",
                 "Guadeloupe", "Martinique",
                 "Guam", "Northern Mariana Islands",
                 "Puerto Rico", "Virgin Islands (U.S.)"),
                 pop = c(1452883897, 7632334, 669037,
                         400276, 367507,
                         172069, 49551,
                         3252407, 103910))


?duplicated()

tmp <- filter(spi_rgn, year == 2022)
sum(duplicated(tmp$Country))

sum(duplicated(spi_rgn[, c('Country','year')]))


spi_rgn <- spi_rgn %>%
  left_join(pop_weights, by = "Country") %>%
  mutate(pop = ifelse(is.na(pop), 1, pop)) %>%
  group_by(rgn_id, rgn_name, year) %>%
  dplyr::summarize(score = weighted.mean(score, pop, na.rm=TRUE),
            method = paste(unique(method), collapse=" "),
            gapfill = weighted.mean(gapfill, pop, na.rm=TRUE))%>%
  ungroup() %>% 
  dplyr::mutate(year = as.numeric(year))


```

